todo/base/urls.py
from django.urls import path

from .views import index, create, edit, delete

app_name = 'base'
urlpatterns = [
    path('', index, name='home'),
    path('create/', create, name='create'),
    path('edit/<int:todo_id>', edit, name='edit'),
    path('delete/<int:todo_id>', delete, name='delete'),
]

todo/todo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('base.urls')),
]

todo/base/models.py
from django.db import models

class Todo(models.Model):
    name=models.CharField(max_length=80)
    description=models.TextField()
    status=models.CharField(max_length=18)

todo/base/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpRequest

from .models import Todo


def index(request):
    context = {'todos': Todo.objects.all()}
    return render(request, 'index.html', context=context)


def create(request: HttpRequest):
    if request.method == 'POST':
        Todo.objects.create(name=request.POST.get('name'), description=request.POST.get(
            'description'), status=request.POST.get('status'))
        return redirect('base:home')
    return render(request, 'create.html')


def edit(request, todo_id):
    to_edit = get_object_or_404(Todo, pk=todo_id)
    if request.method == 'POST':
        to_edit.name = request.POST.get('name')
        to_edit.description = request.POST.get('description')
        to_edit.status = request.POST.get('status')
        to_edit.save()
        return redirect('base:home')

    return render(request, 'edit.html', {'todo': to_edit})


def delete(request, todo_id):
    to_delete = get_object_or_404(Todo, pk=todo_id)
    to_delete.delete()

    return redirect('base:home')

todo/templates/create.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create</title>
    <script src="https://cdn.tailwindcss.com?plugins=forms"></script>
</head>

<body>
    <nav class="bg-gray-800">
        <div class="max-w-7xl px-2 sm:px-6 lg:px-8">
            <div class="relative flex h-16 items-center">
            <div class="absolute inset-y-0 left-0 flex items-center sm:hidden">
            </div>
            <div class="flex flex-1 items-center justify-center sm:items-stretch sm:justify-start">
                <span class="flex flex-shrink-0 w-auto text-white items-center">Todo List</span>
                <div class="hidden sm:ml-6 sm:block">
                <div class="flex space-x-4">
                    <a href="{% url 'base:home' %}" class="rounded-md px-3 py-2 text-sm font-medium text-gray-300 hover:bg-gray-700 hover:text-white">Home</a>
                    <a href="{% url 'base:create' %}" class="rounded-md bg-gray-900 px-3 py-2 text-sm font-medium text-white" aria-current="page">Create</a>
                </div>
                </div>
            </div>
            </div>
        </div>
        
        <!-- Mobile menu, show/hide based on menu state. -->
        <div class="sm:hidden" id="mobile-menu">
            <div class="space-y-1 px-2 pb-3 pt-2">
            <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
            <a href="{% url 'base:home' %}" class="block rounded-md px-3 py-2 text-base font-medium text-gray-300 hover:bg-gray-700 hover:text-white">Home</a>
            <a href="{% url 'base:create' %}" class="block rounded-md px-3 py-2 text-base font-medium bg-gray-900 text-white" aria-current="page">Create</a>
            </div>
        </div>
        </nav>
      
    <h1 class="text-5xl border-b border-gray-900/10 pb-4 pl-8 mt-8">Create Todo</h1>

    <form class="p-8" method="POST">
        {% csrf_token %}
        <div class="space-y-12">
            <div class="border-b border-gray-900/10 pb-12">
                <div class="mt-2 grid grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6">
                    <div class="sm:col-span-4">
                        <label for="task-name" class="block text-sm font-medium leading-6 text-gray-900">Name</label>
                        <div class="mt-2">
                            <div
                                class="flex rounded-md shadow-sm ring-1 ring-inset ring-gray-300 focus-within:ring-2 focus-within:ring-inset focus-within:ring-indigo-600 sm:max-w-md">
                                <input type="text" name="name" id="task-name"
                                    class="block flex-1 border-0 bg-transparent py-1.5 pl-1 text-gray-900 placeholder:text-gray-400 focus:ring-0 sm:text-sm sm:leading-6">
                            </div>
                        </div>
                    </div>

                    <div class="col-span-full">
                        <label for="task-description"
                            class="block text-sm font-medium leading-6 text-gray-900">Description</label>
                        <div class="mt-2">
                            <textarea id="task-description" name="description" rows="3"
                                class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"></textarea>
                        </div>
                    </div>

                    <div class="sm:col-span-3">
                        <label for="status" class="block text-sm font-medium leading-6 text-gray-900">Status</label>
                        <div class="mt-2">
                            <select id="status" name="status" autocomplete="task-status"
                                class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:max-w-xs sm:text-sm sm:leading-6">
                                <option selected value="Done">Done</option>
                                <option value="In Progress">In Progress</option>
                                <option value="Not Done">Not Done</option>
                            </select>
                        </div>
                    </div>

                </div>
            </div>
        </div>

        <div class="mt-6 flex items-center gap-x-6">
            <button type="submit"
                class="rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Save</button>
            <button type="button" class="text-sm font-semibold leading-6 text-gray-900">Cancel</button>
        </div>
    </form>

</body>

</html>

todo/templates/edit.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create</title>
    <script src="https://cdn.tailwindcss.com?plugins=forms"></script>
</head>

<body>
    <nav class="bg-gray-800">
        <div class="max-w-7xl px-2 sm:px-6 lg:px-8">
            <div class="relative flex h-16 items-center">
            <div class="absolute inset-y-0 left-0 flex items-center sm:hidden">
            </div>
            <div class="flex flex-1 items-center justify-center sm:items-stretch sm:justify-start">
                <span class="flex flex-shrink-0 w-auto text-white items-center">Todo List</span>
                <div class="hidden sm:ml-6 sm:block">
                <div class="flex space-x-4">
                    <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
                    <a href="{% url 'base:home' %}" class="rounded-md px-3 py-2 text-sm font-medium text-gray-300 hover:bg-gray-700 hover:text-white">Home</a>
                    <a href="{% url 'base:create' %}" class="rounded-md px-3 py-2 text-sm font-medium text-gray-300 hover:bg-gray-700 hover:text-white">Create</a>
                </div>
                </div>
            </div>
            </div>
        </div>
        
        <!-- Mobile menu, show/hide based on menu state. -->
        <div class="sm:hidden" id="mobile-menu">
            <div class="space-y-1 px-2 pb-3 pt-2">
            <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
            <a href="{% url 'base:home' %}" class="block rounded-md px-3 py-2 text-base font-medium text-gray-300 hover:bg-gray-700 hover:text-white">Home</a>
            <a href="{% url 'base:create' %}" class="block rounded-md px-3 py-2 text-base font-medium text-gray-300 hover:bg-gray-700 hover:text-white">Create</a>
            </div>
        </div>
        </nav>
      
    <h1 class="text-5xl border-b border-gray-900/10 pb-4 pl-8 mt-8">Edit Todo</h1>

    <form class="p-8" method="POST">
        {% csrf_token %}
        <div class="space-y-12">
            <div class="border-b border-gray-900/10 pb-12">
                <div class="mt-2 grid grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6">
                    <div class="sm:col-span-4">
                        <label for="task-name" class="block text-sm font-medium leading-6 text-gray-900">Name</label>
                        <div class="mt-2">
                            <div
                                class="flex rounded-md shadow-sm ring-1 ring-inset ring-gray-300 focus-within:ring-2 focus-within:ring-inset focus-within:ring-indigo-600 sm:max-w-md">
                                <input type="text" name="name" id="task-name" value="{{ todo.name }}"
                                    class="block flex-1 border-0 bg-transparent py-1.5 pl-1 text-gray-900 placeholder:text-gray-400 focus:ring-0 sm:text-sm sm:leading-6">
                            </div>
                        </div>
                    </div>

                    <div class="col-span-full">
                        <label for="task-description"
                            class="block text-sm font-medium leading-6 text-gray-900">Description</label>
                        <div class="mt-2">
                            <textarea id="task-description" name="description" rows="3"
                                class="block w-full text-left rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6">{{ todo.description }}</textarea>
                        </div>
                    </div>

                    <div class="sm:col-span-3">
                        <label for="status" class="block text-sm font-medium leading-6 text-gray-900">Status</label>
                        <div class="mt-2">
                            <select id="status" name="status" autocomplete="task-status"
                                class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:max-w-xs sm:text-sm sm:leading-6">
                                <option {% if todo.status == 'Done' %} selected {% endif %}>Done</option>
                                <option {% if todo.status == 'In Progress' %} selected {% endif %}>In Progress</option>
                                <option {% if todo.status == 'Not Done' %} selected {% endif %}>Not Done</option>
                            </select>
                        </div>
                    </div>

                </div>
            </div>
        </div>

        <div class="mt-6 flex items-center gap-x-6">
            <button type="submit"
                class="rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Save</button>
            <button type="button" class="text-sm font-semibold leading-6 text-gray-900">Cancel</button>
        </div>
    </form>

</body>

</html>

todo/templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>

<body>
    <nav class="bg-gray-800">
        <div class="max-w-7xl px-2 sm:px-6 lg:px-8">
            <div class="relative flex h-16 items-center">
            <div class="absolute inset-y-0 left-0 flex items-center sm:hidden">
            </div>
            <div class="flex flex-1 items-center justify-center sm:items-stretch sm:justify-start">
                <span class="flex flex-shrink-0 w-auto text-white items-center">Todo List</span>
                <div class="hidden sm:ml-6 sm:block">
                <div class="flex space-x-4">
                    <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
                    <a href="{% url 'base:home' %}" class="rounded-md bg-gray-900 px-3 py-2 text-sm font-medium text-white" aria-current="page">Home</a>
                    <a href="{% url 'base:create' %}" class="rounded-md px-3 py-2 text-sm font-medium text-gray-300 hover:bg-gray-700 hover:text-white">Create</a>
                </div>
                </div>
            </div>
            </div>
        </div>
        
        <!-- Mobile menu, show/hide based on menu state. -->
        <div class="sm:hidden" id="mobile-menu">
            <div class="space-y-1 px-2 pb-3 pt-2">
            <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
            <a href="{% url 'base:home' %}" class="block rounded-md bg-gray-900 px-3 py-2 text-base font-medium text-white" aria-current="page">Home</a>
            <a href="{% url 'base:create' %}" class="block rounded-md px-3 py-2 text-base font-medium text-gray-300 hover:bg-gray-700 hover:text-white">Create</a>
            </div>
        </div>
        </nav>
      
    <h1 class="text-5xl border-b border-gray-900/10 pb-4 pl-8 mt-8">Home</h1>

    <table class="table-auto w-full m-4 text-center border-b border-black">
        <thead class="text-white bg-gray-700">
            <tr>
                <th scope="col" class="px-6 py-3">S.N.</th>
                <th scope="col" class="px-6 py-3">Description</th>
                <th scope="col" class="px-6 py-3">Name</th>
                <th scope="col" class="px-6 py-3">Status</th>
                <th scope="col" class="px-6 py-3">Action</th>
            </tr>
        </thead>
        <tbody>
            {% for todo in todos %}
            <tr class="even:bg-cyan-100">
                <th scope="row" class="px-6 py-3">{{ forloop.counter }} </th>
                <td class="px-6 py-4">{{ todo.name }} </td>
                <td class="px-6 py-4">{{ todo.description }}</td>
                <td class="px-6 py-4">{{ todo.status }}</td>
                <td class="px-6 py-4">
                    <a href=" {% url 'base:edit' todo_id=todo.id %} ">
                        <button
                            class="px-4 py-1 text-sm text-white font-semibold rounded-xl border bg-slate-700 hover:text-white hover:bg-blue-600 hover:border-transparent focus:outline-none focus:ring-2 focus:ring-gray-600 focus:ring-offset-2">
                            Edit
                        </button>
                    </a>

                    <a href=" {% url 'base:delete' todo_id=todo.id %}">
                        <button
                            class="px-4 py-1 text-sm text-gray-300 font-semibold rounded-xl border bg-red-500 hover:bg-red-700 hover:text-white hover:border-transparent focus:outline-none focus:ring-2 focus:ring-gray-600 focus:ring-offset-2">
                            Delete
                        </button>
                    </a>

                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <a href="{% url 'base:create' %}"
        class="ml-4 px-3 py-2 text-sm text-white font-semibold rounded-md border bg-emerald-500 hover:text-white hover:bg-green-600 hover:border-transparent focus:outline-none focus:ring-2 focus:ring-gray-600 focus:ring-offset-2">
        Create New
    </a>

</body>

</html>